my_blogsite/blogsite/urls.py
from django.urls import path
from . import views

app_name = 'blogsite'

urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:id>/<int:month>/<int:day>/<slug:post>/', 
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', 
         views.post_share, name='post_share'),
    path('<int:post_id>/comment',
         views.post_comment, name='post_comment'),
]

my_blogsite/my_blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogsite/', include('blogsite.urls', namespace='blogsite')),
]

my_blogsite/blogsite/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=255, unique=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    phone = models.IntegerField(null=True)
    joined_date = models.DateField(null=True)

    # To change the string representation, we have to define the __str__() function of the Member Model in models.py
    def __str__(self):
        return f"{self.firstname} {self.lastname}"

# Create a model manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft',
        PUBLISHED = 'published', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='published_at')
    author = models.ForeignKey('User', on_delete=models.CASCADE, related_name='blog_posts', default=1)
    body = models.TextField()
    published_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=9, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager() # The default manager
    published = PublishedManager() # A custom manager for published posts

    class Meta:
        ordering = ['-published_at']
        indexes = [
            models.Index(fields=['published_at']),
        ]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('blogsite:post_detail', 
                       args=[self.published_at.year,
                             self.published_at.month,
                             self.published_at.day,
                             self.slug,]
    )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['created_at']),
        ]

    def __str__(self) -> str:
        return f"Comment by {self.name} on {self.post}"

my_blogsite/blogsite/forms.py
from django import forms

from . import models


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to_email = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
    def clean_to(self):
        to_emails = self.cleaned_data.get('to_email')
        if not to_emails:
            raise forms.ValidationError('You must enter at least one recipient email.')
        if len(to_emails.split()) > 5:
            raise forms.ValidationError('You can only enter up to five recipient emails.')
        return to_emails
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['name', 'email', 'body']

my_blogsite/blogsite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.views.decorators.http import require_POST

from . import models
from . import forms


# Using the generic ListView
class PostListView(ListView):
    """Alternative post list view"""
    queryset = models.Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blogsite/post/list.html'

# Create your views here.
def post_list(request):
    post_list = models.Post.published.all()
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    template = loader.get_template('list.html')
    context = {
        'posts': posts
    }

    return HttpResponse(template.render(context, request))

def post_detail(request, year, month, day, post):
    post = get_object_or_404(models.Post,
        status=models.Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    # List of active comments for this post
    comments = post.comments.filter(active=True)   # We have added a QuerySet to retrieve all active comments for the post,
    # Form for users to comment
    form = forms.CommentForm()
    
    template = loader.get_template('detail.html')
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }

    return HttpResponse(template.render(context, request))
    # try:
    #     post = models.Post.published.get(id=id)
    #     template = loader.get_template('detail.html')
    #     context = {
    #         'post_detail': post
    #     }
    # except models.Post.DoesNotExist:
    #     raise Http404("No post found")
    # return HttpResponse(template.render(context, request))


def post_share(request, post_id):
    post = get_object_or_404(models.Post, id=post_id, status=models.Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = forms.EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends reading '{post.title}'"
            message = f"Read '{post.title}' at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'noreply@example.com', [cd['email']])
            sent = True
    else:
        form = forms.EmailPostForm()
        context = {
            'post': post,
            'form': form,
            'sent': sent,
        }
    template = loader.get_template('share.html')

    return HttpResponse(template.render(request, context))
    # send email or other sharing logic here
    # return HttpResponseRedirect(post.get_absolute_url())

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(models.Post, id=post_id, status=models.Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = forms.CommentForm(data=request.POST)
    if form.is_valid():
        # Create a comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the comment to the post
        comment.post = post
        # Save the comment to the database
        comment.save()
    template = loader.get_template('comment.html')
    context = {
        'comment': comment,
        'post': post,
        'form': form,
    }
    
    return HttpResponse(template.render(request, context))

my_blogsite/blogsite/templates/blog/base.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>

    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}

    <p>
        <a href="{% url "blogsite:post_share" post.id %}">
            Share this post
        </a>
    </p>
    
    {% include "pagination.html" with page=posts %}
{% endblock %}

my_blogsite/blogsite/templates/blog/includes/comment_form.html
<h2>Add a new comment</h2>

<form action="{% url "blog:post_comment" post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

my_blogsite/blogsite/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blogsite/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

my_blogsite/blogsite/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>

    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    {{ post.body|linebreaks }}

    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }}</p>
            <p class="comment-date">{{ comment.created }}</p>
            <p class="comment-body">{{ comment.body|linebreaks }}</p>
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}

    {% include "bogsite/includes/comment_form.html" %}
{% endblock %}

my_blogsite/blogsite/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

    <h1>My Blog</h1>

    {% for post in posts %}

        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>

        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>

        {{ post.body|truncatewords:30|linebreaks }}

    {% endfor %}

    {% include "pagination.html" with page=page_obj %}

{% endblock %}

my_blogsite/blogsite/templates/blog/post/pagination.html

<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

my_blogsite/blogsite/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email sent successfully</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to_email }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Send email</button>
        </form>
    {% endif %}
{% endblock %}